site_name: My Research Notes
site_description: 学习与论文笔记
site_author: Meteor Tequila
docs_dir: docs
site_dir: site

theme:
  name: material
  # features:
  #   - navigation.instant
  #   - navigation.expand
  # palette:
  #   scheme: default

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true          # 使用 KaTeX 渲染
  - pymdownx.superfences     # 支持多语言代码块
  - pymdownx.highlight       # 代码块高亮
  - pymdownx.arithmatex      # 数学公式支持
  - pymdownx.inlinehilite    # 行内高亮

# plugins:
#   - search

# nav:
#   - 首页: index.md
#   - 学习笔记:
#       - 示例笔记: notes/example.md
#   - 项目展示:
#       - 照片集: projects/gallery.md

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/highlight.js@11.8.0/styles/github.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/highlight.js@11.8.0/lib/highlight.js
#   - javascripts/math-and-highlight.js
