site_name: My Research Notes
site_description: 学习与论文笔记
site_author: Meteor Tequila

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.indexes

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex  # 数学公式
  - pymdownx.superfences # 代码块增强

plugins:
  - search

nav:
  - 首页: index.md
  - 学习笔记:
      - 示例笔记: notes/example.md
  - 项目展示:
      - 照片集: projects/gallery.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/contrib/auto-render.min.js
  - javascripts/math.js  # 创建

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.css

